---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-security-evaluator
  namespace: workload-security-evaluator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-security-evaluator
  template:
    metadata:
      labels:
        app: workload-security-evaluator
    spec:
      containers:
      - image: confusedcrib/workload-security-evaluator:latest
        name: workload-security-evaluator
        env:
        - name: AWS_ACCESS_KEY_ID
          value: AKIAIOSFODNN72HYSDD8
        - name: AWS_SECRET_ACCESS_KEY
          value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYeh2g7ykyu8
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: docker-socket
      serviceAccountName: workload-security-evaluator-sa
---
kind: Service
apiVersion: v1
metadata:
  name: workload-security-evaluator
  namespace: workload-security-evaluator
spec:
  type: NodePort
  selector:
    app: workload-security-evaluator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: ssh
    port: 22
    targetPort: 22
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workload-security-evaluator-role
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts", "serviceaccounts/token"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workload-security-evaluator-role-binding
subjects:
- kind: ServiceAccount
  name: workload-security-evaluator-sa
  namespace: workload-security-evaluator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: workload-security-evaluator-role
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-security-evaluator-sa
  namespace: workload-security-evaluator